### ISSUE TITLE
Documentation Link Broken on Main Page under Installation

### ISSUE THREAD

**Issue by mark7five7** [markdomansky/WebJEA#1]
The Documentation link on the main page under installation gets a 404 error.

**Comment by markdomansky** [comment]
[fixed](9013f4dc7da1def1734c271a3ac74b416188726f)  admittedly, there's no documentation at the moment.  Please check out the [Demo Materials](https://github.com/markdomansky/WebJEADemo).  I'll try to get some documentation up quickly.
