### ISSUE TITLE
Using the WebJEA user's hostname?

### ISSUE THREAD

**Issue by stephencrowther-bond** [markdomansky/WebJEA#14]
Is it possible to use the WebJEA user's hostname in a script?
For example, is it possible to show the user their hostname (or IP address) in the script output:
`Write-Host $WebJEAuserHostname`

This does not seem to work in v0.9.149.

**Comment by markdomansky** [comment]
Have you added $WebJEAHostname to your parameters?
You must define a WebJEAHostname or WebJEAUsername parameter if you want to use those.

**Comment by markdomansky** [comment]
overview.ps1 is an onload script.  Onload scripts don't accept parameters.
Are you seeing the parameter on your other script when you click submit?
If not, can you include the script, or at least the parameters section of your script that you're having issues with?

**Comment by stephencrowther-bond** [comment]
Thank you Mark, I understand now. 
I had copied validate.ps1 for my script.
I removed the # from the line declaring [string]$WEBJEAHostname 

Original:

`#special variables for WebJEA`
`#[Parameter(Mandatory)] [string]$WEBJEAUsername="$($env:userdomain)\$($env:username)", #passes the domain\username to the script`
`#[Parameter(Mandatory)] [string]$WEBJEAHostname=($env:computername), #passes the client machine from asp.net, will return IP address some times`

Removed # like this:

`#special variables for WebJEA`
`#[Parameter(Mandatory)] [string]$WEBJEAUsername="$($env:userdomain)\$($env:username)", #passes the domain\username to the script`
`[Parameter(Mandatory)] [string]$WEBJEAHostname=($env:computername), #passes the client machine from asp.net, will return IP address some times`

So now I can use:

`Write-Output $WEBJEAHostname`

The IP Address is now also appearing in the WebJEA log files.

**Comment by markdomansky** [comment]
Glad you got it working!
