### ISSUE TITLE
Changing Application Pool name

### ISSUE THREAD

**Issue by stephencrowther-bond** [markdomansky/WebJEA#15]
I attempted to change the Application Pool name in the DSC config (to PoSh) and received the following DSC errors (webjea-0.9.149.18160-rev1):

`VERBOSE: [MYSERVERNAME]:                            [[xWebAppPool]WebJEA_IISAppPool] APPPOOL object "WebJEA" changed`
`VERBOSE: [MYSERVERNAME]: LCM:  [ End    Set      ]  [[xWebAppPool]WebJEA_IISAppPool]  in 0.5150 seconds.`
`VERBOSE: [MYSERVERNAME]: LCM:  [ End    Resource ]  [[xWebAppPool]WebJEA_IISAppPool]`
`VERBOSE: [MYSERVERNAME]: LCM:  [ Start  Resource ]  [[Script]ChangeAppPoolIdentity]`
`VERBOSE: [MYSERVERNAME]: LCM:  [ Start  Test     ]  [[Script]ChangeAppPoolIdentity]`
**`Cannot find path 'IIS:\AppPools\PoSh' because it does not exist.`
`    + CategoryInfo          : ObjectNotFound: (IIS:\AppPools\PoSh:) [], CimException`
`    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand`
`    + PSComputerName        : MYSERVERNAME`**

`VERBOSE: [MYSERVERNAME]: LCM:  [ End    Test     ]  [[Script]ChangeAppPoolIdentity]  in 0.2040 seconds.`
**`The PowerShell DSC resource '[Script]ChangeAppPoolIdentity' with SourceInfo`
`'C:\Source\DSCConfig.inc.ps1::36::9::Script' threw one or more non-terminating errors while running the`
`Test-TargetResource functionality. These errors are logged to the ETW channel called`
`Microsoft-Windows-DSC/Operational. Refer to this channel for more details.`
`    + CategoryInfo          : InvalidOperation: (:) [], CimException`
`    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider`
`    + PSComputerName        : MYSERVERNAME`**

...

`VERBOSE: [MYSERVERNAME]: LCM:  [ End    Set      ]  [[File]WebJEA_ScriptsContent]  in 0.0320 seconds.`
`VERBOSE: [MYSERVERNAME]: LCM:  [ End    Resource ]  [[File]WebJEA_ScriptsContent]`
`VERBOSE: [MYSERVERNAME]: LCM:  [ End    Set      ]`
**`The SendConfigurationApply function did not succeed.`
`    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException`
`    + FullyQualifiedErrorId : MI RESULT 1`
`    + PSComputerName        : MYSERVERNAME`**

`VERBOSE: Operation 'Invoke CimMethod' complete.`
`VERBOSE: Time taken for configuration job to complete is 262.714 seconds`

**Comment by stephencrowther-bond** [comment]
I renamed the WebJEA app pool to PoSh and then re-ran DSCDeploy.ps1.
DSC ran without errors and I ended up with a PoSh app pool properly configured with the MSA identity, and also a WebJEA app pool unassigned to the application and without a set Identity. The application called PoSh is now also set to use the app pool called PoSh.

**Comment by andrewdiaz951** [comment]
So I am getting the same 
`The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : WEBJEA`

I renamed app pools in both the deploy and config files and still get the same error.  Do you have any other recommendations?

**Comment by markdomansky** [comment]
Can you post your DSC configuration?  I suspect you may need to modify the DSCConfig.ps1 file.  There is an xWebAppPool resource.  In it is a Name property.  There should read $node.WebAppPoolName instead of being statically set.
