### ISSUE TITLE
Setting Role and Session capabilities

### ISSUE THREAD

**Issue by lastusrnameon3** [markdomansky/WebJEA#16]
Using the guide here: https://docs.microsoft.com/en-us/powershell/jea/role-capabilities

I've created a new Role Capabilities and Session configuration file to limit user access to only a few CmdLets. 
How do i config WebJea to use the new configurations ?

**Comment by markdomansky** [comment]
WebJEA doesn't depend on JEA, but will work with it.  Your configuration would look something like this:

WebJEA configured to use ServiceAccount1
ServiceAccount1 granted access to the JEA endpoint
PS1 configured to accept parameters needed, and calls the JEA endpoint (invoke-command or similar)
PS1 configured on WebJEA
Users granted access to WebJEA

The user would go to WebJEA, fill out the parameters, then click submit.  WebJEA would execute the command and return the output.

If you're looking for a console interface on the web, look into [PowerShell Web Access](https://docs.microsoft.com/en-us/powershell/scripting/components/web-access/install-and-use-windows-powershell-web-access?view=powershell-6).
