### ISSUE TITLE
Logging who runs Web JEA Task

### ISSUE THREAD

**Issue by joevanmaldegiam** [markdomansky/WebJEA#2]
Hello,

I am getting this tool setup and I'd like to add logging of what user ran the webjea task in the returned output.  I see the webjea-usage.log shows this information but it would be nice to have it in the jobs themselves so I can send notifications to our logging infrastructure.  Is this possible?

Great tool, thank you for building it!

**Comment by markdomansky** [comment]
Good news, this is already built-in!
Just add parameters [string]$WebJEAUsername and [string]$WebJEAHostname to get the user and hostname sent by the ASP.NET.  In my experience, hostname is often just IP address.
