### ISSUE TITLE
AuthorizationManager Failed

### ISSUE THREAD

**Issue by slm04747** [markdomansky/WebJEA#22]
After fighting with IIS for a while and replacing the gMSA in the AppPool with our default Web app account, I was able to get to the login page. I added my domain\account to the Permitted groups for teh overview command. The page displays, but I am getting an AuthorizationManager check failed. Any suggestions on resolving this error?

Thanks
Steve Moss
Pomona College

**Comment by markdomansky** [comment]
I know this was from a long time ago.  I don't know how I missed it.  If you're still interested in this, can you clarify the error?  What is the screen showing, what do the logs show?
