### ISSUE TITLE
Page load hangs when Parameter documentation contains single quote character

### ISSUE THREAD

**Issue by jrennert** [markdomansky/WebJEA#3]
The server experiences high CPU utilization and the page load hangs when the .PARAMETER documentation contains a single quote.

Steps to re-create:

- Save the script below into a .ps1 
- Add a command for it to WebJEA 
- Navigate to the command in WebJEA

```
<#
.SYNOPSIS
Here is a brief description

.DESCRIPTION
Here is the more detailed description

.PARAMETER Test
    This is the script's test value

.NOTES
Version:          1.0
Author:           Jrennert
Creation Date:    5/16/2018
Purpose/Change:   Initial release
#>
param(
[string]$test
)
Write-Host "You ran the script"

```

**Comment by markdomansky** [comment]
I'll take a look and see what I can do.
