### ISSUE TITLE
System.Exception: Could not read config file

### ISSUE THREAD

**Issue by checkso** [markdomansky/WebJEA#30]
Hi there, 

I just installed WebJea and get the following error message. 

> [Exception: Could not read config file]    WebJEA._default.Page_Load(Object sender, EventArgs e) in C:\prj\WebJEA CE\WebJEA\WebJEA\default.aspx.vb:35    System.Web.UI.Control.OnLoad(EventArgs e) +106    System.Web.UI.Control.LoadRecursive() +68    System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +3785
> --
> 

Permissions for the GMSA are granted to the wwwroot folder.

Any idea what else I can check? I am also a bit lost with the path in the error message (c:\prj\...) This is not the path I installed webjea to.

**Comment by markdomansky** [comment]
look at the web.config to see where webjea is looking for the config file.
You should see something like this:
  <applicationSettings>
    <WebJEA.My.MySettings>
      <setting name="configfile" serializeAs="String">
        <value>**C:\WebJEA\config.json**</value>
      </setting>
    </WebJEA.My.MySettings>
  </applicationSettings>

What is the current value?
Is that file present?

**Comment by checkso** [comment]
This was in the file:

<WebJEA.My.MySettings>
      <setting name="configfile" serializeAs="String">
        <value>C:\scripts\config.json</value>
      </setting>
    </WebJEA.My.MySettings>

I now changed it to the folder WebJEA was installed to, it is working but now I get "You do not have access to this command."

Somehow I guess to install it to a different folder not so easy. Maybe I just reinstall to the standard folder :)

**Comment by checkso** [comment]
```
2020-03-23 14:10:10.0271|Trace|397||Company\UserName|GetFileContent: C:\Company\WebJEA\scripts\config.json
2020-03-23 14:10:10.0271|Trace|398||Company\UserName|GroupFinder: GetSID: Cached Contexts: 1
2020-03-23 14:10:10.0271|Trace|399||Company\UserName|GroupFinder: GetSID: Input: .\Administratoren
2020-03-23 14:10:10.0271|Trace|400||Company\UserName|GroupFinder: GetSID: Found cached Context: .
2020-03-23 14:10:10.0427|Trace|401||Company\UserName|GroupFinder: GetSID: Cached Contexts: 1
2020-03-23 14:10:10.0427|Trace|402||Company\UserName|GroupFinder: GetSID: Input: .\Administratoren
2020-03-23 14:10:10.0427|Trace|403||Company\UserName|GroupFinder: GetSID: Found cached Context: .
2020-03-23 14:10:10.0427|Trace|404||Company\UserName|IsGlobalUser: False
2020-03-23 14:10:10.0427|Trace|405||Company\UserName|GetMenu: IsGlobalUser: False
2020-03-23 14:10:10.0427|Trace|406||Company\UserName|Building Menu 
2020-03-23 14:10:10.0427|Warn|407||Company\UserName|User Company\UserName requested page they don't have access to overview. redirecting to overview
2020-03-23 14:10:10.0427|Debug|408||Company\UserName|PSCmd|Init overview
```

That is the log I can see. Don't know why this error appears but I am local administrator on the machine

**Comment by markdomansky** [comment]
So the initial problem is that the IIS account you used (gMSA hopefully), did not have access to the target c:\scripts folder.  It would need to be given read access.  The config file and related scripts should not be in the same folders.  There should be an iis folder with the .aspx files and related content, and then a scripts folder with the config.json and powershell scripts.  I would be concerned about the security of the config and powershell scripts.

I think your new issue is that the config.json defaults to "Administrators" as having access and your OS uses Administrator**en**.  If you change config.json to match, it should start working.

**Comment by checkso** [comment]
So what I did was:
1. Created gMSA and tested it can connect
2. Extract WebJEA to C:\Company\WebJEA
3. Adjusted the DSCDeploy.ps1 to the path above and deployed--> Initial Error Message 
4. After your hint with the web.config I changed the values (from _C:\scripts_ to _C:\Company\WebJEA_), as well as the config.json and deployed again --> Now it works

Should it be like this?

About the Administrators -> That is what I thought as well. Changed it to "Administratoren" but same issue
Does this maybe not work If I am not directly member of Administrators, because I am within a group which is assigned to Administrators.

**Comment by checkso** [comment]
My DSCDeploy.ps1

```
$MyData = @{
    AllNodes = @(
        @{
            NodeName = '*'
            WebAppPoolName = 'WebJEA'
            AppPoolUserName = 'Company.office\GMSAWebJea$'
            AppPoolPassword = "" #no credential data is actually password because we're using gMSAs
            #if you use a non-msa, use another method to set the apppool identity
            WebJEAIISURI = 'WebJEA'
            WebJEAIISFolder = 'C:\inetpub\wwwroot\webjea'
            WebJEASourceFolder = 'C:\Company\WebJEA'
            WebJEAScriptsFolder = 'C:\Company\WebJEA\scripts'
            WebJEAConfigPath = 'C:\Company\WebJEA\scripts\config.json' #must be in webjeascriptsfolder
            WebJEALogPath = 'C:\Company\WebJEA\scripts'
            WebJEA_Nlog_LogFile = "C:\Company\WebJEA\scripts\webjea.log"
            WebJEA_Nlog_UsageFile = "C:\Company\WebJEA\scripts\webjea-usage.log"
        },
        @{
            NodeName = 'MFJEA'
            Role = 'WebJEAServer'
            MachineFQDN = 'mfjea.Company.office'
            CertThumbprint = '?911fba1ba1c1a88ddb9e8765b9d9e13dcf4c0684'
        }
    )
}
```

**Comment by markdomansky** [comment]
> Does this maybe not work If I am not directly member of Administrators, because I am within a group which is assigned to Administrators.

Nested groups work fine.  However, it wouldn't hurt to try a non-nested group just for troubleshooting.

The gMSA will also need write access to the 2 log files.

So just to clarify, which error are you getting now?

**Comment by checkso** [comment]
it looks like everything is working fine. Just a bit strange that the config.json is always overwritten by the one in the _Starterfiles_ folder.

But besides this everything ist fine.

Maybe the installation guide has to be adjusted a bit. Because only renaming the DSCDeploy.ps1 is not enough.

**Comment by markdomansky** [comment]
This seems to occur when you are leveraging DSC for other system configurations in a persistent, refresh mode.
The DSC install configuration is not intended for repeated execution.  There are a couple solutions:
* Setting the LCM refreshmode to disabled would disable it.
* you could make your changes to the webjea config in the source
* setting matchsource = $false in webjea dsc config.
