### ISSUE TITLE
How to force elevated powershell session and PS 7?

### ISSUE THREAD

**Issue by EtsHere** [markdomansky/WebJEA#33]
Restarting a server on local server fails with not enough permission.
Also how to run the session in Powershell 7.

**Comment by markdomansky** [comment]
Can you clarify the first question?  If you're wanting to start a session elevated, that shouldn't be necessary, provided you grant the service account sufficient privileges.  I suppose in the right environment, you could also disable UAC, but that's generally not recommended.

As far as PowerShell 7, it isn't directly supported.  However, it should be possible to initiate a new-pssession or Invoke-Command to PS 7.  I am looking at PS 7 support, but it's going to be a full rewrite in a language I'm only generally familiar with.

**Comment by EtsHere** [comment]
Starting service on a local machine where WebJEA is installed does not work. When opening elevated powershell the restart works. The account is a local admin.

**Comment by markdomansky** [comment]
A couple searches suggest the following:
```Start-Process powershell.exe -filepath 'xxxx' -Verb RunAs```

A little bit of abstraction by calling out to another script may work here.

**Comment by RStoddart** [comment]
PowerShell 7 is stared with PWSH.EXE
so both Windows PowerShell and PowerShell Core could co-exist.

**Comment by markdomansky** [comment]
WebJEA does not run "powershell.exe", and therefore cannot run "pwsh.exe" either.  WebJEA instantiates powershell via DLL, and then executes the commands within an instance of the DLL.
PowerShell 7 is on the roadmap, but will require a substantial amount of work.

**Comment by KodySalak** [comment]
Coming back on this 4 years later - I was able to accomplish this by essentially making a bootstrap PowerShell 5 script that will call the 7... but I also needed to make the app pool run as local system to get anything that needs elevation to work. 

**PLEASE BE CAUTIOUS: LOCAL SYSTEM ON AN IIS WEBPAGE IS DANGEROUS. DO _NOT_ RUN THIS INTERNET FACING!!**
