### ISSUE TITLE
Validation of viewstate MAC failed

### ISSUE THREAD

**Issue by MarcelPalme** [markdomansky/WebJEA#36]
Hi,

Hello, I installed webjea on an IIS 10 (Server 2019) using dsc. The website opens but when I click Submit on the Overview page I get an error message "Validation of viewstate MAC failed". How can I fix this? Sincerely, Marcel

**Comment by markdomansky** [comment]
Is this the default overview page?

**Comment by MarcelPalme** [comment]
yes that was on the overview page. I've already solved the problem. I had opened the page with IE - in IE apparently there were no authorizations to execute java in chrome everything worked

**Comment by MarcelPalme** [comment]
Problem solved
