### ISSUE TITLE
$WebJEAuserHostname is empty

### ISSUE THREAD

**Issue by amnich** [markdomansky/WebJEA#37]
The variable $WebJEAuserHostname is empty.
In the example script "validate.ps1" the variable $WebJEAuserHostname is not shown in the PSBoundParameters list.
I also tried to display it manually in another place, but it is empty.
I have the latest version 1.1.157.

EDIT: 12.10.2020 10:48 UTC 
In the PSWebHelper.vb I only found the WEBJEAHOSTNAME 
![image](https://user-images.githubusercontent.com/12390100/95738327-56b9c480-0c89-11eb-8550-a36367570d5a.png)

EDIT: 12.10.2020 12:29 UTC
![image](https://user-images.githubusercontent.com/12390100/95746600-5a544800-0c97-11eb-9de2-c95c8aec9492.png)

**Comment by markdomansky** [comment]
That is a typo.  It should be ```$WebJEAuserHostname``` should be ```$WebJEAHostname```.
Probably a search and replace gone haywire.
I have corrected it and updated the package.
