### ISSUE TITLE
Deploy fails on Windows 2016

### ISSUE THREAD

**Issue by thatguytom801** [markdomansky/WebJEA#38]
Need to set TLS version for your deploy script to work:

**[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12**

Doesn't work out of the box on README recommended specs.

Configuring Package Provider
WARNING: MSG:UnableToDownload «https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409» «»
WARNING: Unable to download the list of available providers. Check your internet connection.
WARNING: Unable to download from URI 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409' to ''.
install-packageprovider : No match was found for the specified search criteria for the provider 'nuget'. The package provider requires 'PackageManagement' and 'Provider' tags. Please check if the specified package has the tags.
At C:\Users\tom\Downloads\webjea\DSCDeploy.ps1:33 char:5
+     install-packageprovider -name nuget -minimumversion 2.8.5.201 -fo ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Power...PackageProvider:InstallPackageProvider) [Install-PackageProvider], Exception
    + FullyQualifiedErrorId : NoMatchFoundForProvider,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackageProvider

**Comment by markdomansky** [comment]
This is an interesting question.  This is a system level TLS issue.  PSGallery has moved to TLS1.2 only.  I'll look to see if this can be permanently enabled in DSC.

**Comment by markdomansky** [comment]
I believe this is fixed in the latest release but I'm no longer testing with 2016.
