### ISSUE TITLE
Is it possible use gMSA with Exchange on-premise?

### ISSUE THREAD

**Issue by ommnni** [markdomansky/WebJEA#39]
First of all, I want to say thank you, that's a great job.

But I have one issue with gMSA. Does it work with an on-premise exchange? Is it possible to add gMSA account in exchange on-premise roles?

**Comment by markdomansky** [comment]
So the gMSA is used to run the powershell instance.  I've never tried to access Exchange PowerShell using a gMSA.  I know you can do integrated auth with Exchange.  If you can add the gMSA to the relevant security group (e.g. Exchange User Admins), then you should be able to make the exchange connection.  Give it a try and let me know.

**Comment by ommnni** [comment]
> If you can add the gMSA to the relevant security group (e.g. Exchange User Admins), then you should be able to make the exchange connection.

No, I can't add the gMSA to any Exchange security group.
Instead of the gMSA I've try to use normal winnt account and gave it appropriate rights in Exchange. I've modify DSC config (line 49,50):
                $pool.processModel.userName = 'domain\WebJEAAccount'
                $pool.processModel.password = 'password'
Is it correct?

**Comment by markdomansky** [comment]
This should be correct.
