### ISSUE TITLE
Access to WebJEAUsername in OnloadScript

### ISSUE THREAD

**Issue by amnich** [markdomansky/WebJEA#4]
Access to the $WebJEAUsername in the OnloadScript would be great improvement.

This way I could present information or prepare links for the calling user.

**Comment by markdomansky** [comment]
I definitely hear you.

**Comment by LLIT** [comment]
A quick hack I used:

In default.aspx - first line in the body section:
<div id="HiddenUsername" style="display: none"><asp:LoginName id="LoginName1" runat="server" FormatString ="{0}" /></div>

In startup.js - just at the end:
The following replaces the value for the parameter "**Requester**" in the Powershell Script.

if (document.getElementById("psparam_**Requester**")) {
    document.getElementById("psparam_**Requester**").value = document.getElementById("LoginName1").innerText.split("\\")[1].toUpperCase();
    document.getElementById("psparam_**Requester**").readOnly = true;
}

**Comment by thegreatone91821** [comment]
> A quick hack I used:
> 
> In default.aspx - first line in the body section:
> 
> In startup.js - just at the end:
> The following replaces the value for the parameter "**Requester**" in the Powershell Script.
> 
> if (document.getElementById("psparam_**Requester**")) {
> document.getElementById("psparam_**Requester**").value = document.getElementById("LoginName1").innerText.split("\")[1].toUpperCase();
> document.getElementById("psparam_**Requester**").readOnly = true;
> }

Im a little confused...what did you put in the default.aspx?  All I did was add the following in startup.js:

if (document.getElementById("psparam_Requester")) {
document.getElementById("psparam_Requester").value = document.getElementById("LoginName1").innerText.split("\")[1].toUpperCase();
document.getElementById("psparam_Requester").readOnly = true;
};

**Comment by LLIT** [comment]
The important first line in the body section in default.aspx:
<div id="HiddenUsername" style="display: none"><asp:LoginName id="LoginName1" runat="server" FormatString ="{0}" /></div>

**Comment by thegreatone91821** [comment]
> The important first line in the body section in default.aspx:
> `<div id="HiddenUsername" style="display: none"><asp:LoginName id="LoginName1" runat="server" FormatString ="{0}" /></div>`

Ah okay, I had this... <asp:LoginName ID="LoginName1" runat="server" Visible="false"/> 
which I thought should have worked but when I try to use $Requester variable in an onload.ps1 script, it doesnt seem to find that variable at all. 

Is there anything I am missing? I am not a strong web developer so pardon me if it is something trivial.

**Comment by LLIT** [comment]
I think we need to look into how the onload script is executed. 
For now I only use it in the other scripts. 

Right now i am thinking about a cheat with outputting to JSon an some JS filtering. 
But it will be slower.

**Comment by thegreatone91821** [comment]
> I think we need to look into how the onload script is executed.
> For now I only use it in the other scripts.
> 
> Right now i am thinking about a cheat with outputting to JSon an some JS filtering.
> But it will be slower.

Ah Okay. I thought you were creating a new variable that could be used in an onload script. This would be a HUGE feature, its the one I could leverage hugely. It seems that it would be super easy to implement seeing as that already exists for other scripts using $WebJEAHostname and $webJEAUsername.

**Comment by andrewdiaz951** [comment]
I know this is an old thread but has anyone figured out how to accomplish this?  Even more specifically pass this variable to prefil a field within webjea?

**Comment by phoerr** [comment]
If anyone is still watching this thread, I found a way to see the `$WebJEAUsername` variable in the onload script. 

Here's what my `default.aspx.vb` looks like now, starting on line 116:

```vb
Else 'run the script and display it
    Dim ps As New PSEngine
    Dim pswebonload As New PSWebHelper
    ps.Script = cmd.OnloadScript
    ps.LogParameters = cmd.LogParameters
    'pass in parameters to onload script
    ps.Parameters = pswebonload.getParameters(cmd, Page)
    ps.Run()
    objTelemetry.AddRuntime(ps.Runtime)
    objTelemetry.AddIsOnload(True)

    consoleOnload.InnerHtml = pswebonload.ConvertToHTML(ps.getOutputData)
    ps = Nothing
```

Now, this lets me see the current user in the onload script. From there, I can present a list of options to the end user based on their name, each of which are links to a _second_ script. When clicking on one of these links, it will load the second script with pre-filled parameters.
