### ISSUE TITLE
The computer-specific MOF file for computer 

### ISSUE THREAD

**Issue by A41-Frech** [markdomansky/WebJEA#40]
Hello guys,
before I will break the current file;

Maybe you had similar problems.

```
cd C:\source
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

.\DSCDeploy.ps1
```

After running the deployment script

```
Start-DscConfiguration : The computer-specific MOF file for computer XXXXXXX does not exist in the current directory.
At C:\source\DSCDeploy.ps1:61 char:1
+ Start-DscConfiguration -ComputerName $env:computername -Path .\WebJEA ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-DscConfiguration], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.DesiredStateConfiguration.Commands.StartDscC 
   onfigurationCommand`
```

**Comment by markdomansky** [comment]
Duplicate of #38.

**Comment by dwestness** [comment]
I have the same issue described here. It does not seem to be a duplicate to the linked issue however and I haven't been able to figure out how to work around it

**Comment by dwestness** [comment]
Looks like it created WEB1.MOF and expected <computername>.MOF ... I renamed the file and it seems to be running now actually. I see in the DSCDeploy.ps1 file there is a variable for "NodeName" that is defaulted to WEB1 so i assume that's where it got it from without looking through the code. Perhaps i missed updating that before the run

**Comment by markdomansky** [comment]
You're correct.  The computername WEB1 was not changed.  Glad to hear you got it working.
