### ISSUE TITLE
Changing colors/theme

### ISSUE THREAD

**Issue by Geo-Ron** [markdomansky/WebJEA#41]
@markdomansky ,

I am unable to find documentation on how to change the colors of the WebJEA page.
Any tips?
Changing sidebar.css does not seem to have any effect in my instance...

**Comment by markdomansky** [comment]
The CSS files are the place to go.  There are 3 main CSS files, but there may be additional in the subfolders as part of the bootstrap theme.

**Comment by Geo-Ron** [comment]
Mark, so changing sidebar.css **should** have effect?

**Comment by markdomansky** [comment]
Correct.  If you aren't able to change the color, let me know what you're trying to do and I'll see if I can make a few minutes.  I'm not great at CSS and that was a package I imported, so I can't guarantee I can fix it.

**Comment by Geo-Ron** [comment]
You were right (and I was too)
The style is contained in the main.ss,sidebar.css and psoutput.css

Caching failed on me...

Thanks for you good response.
