### ISSUE TITLE
Encoding errors in WebJEA with german umlauts

### ISSUE THREAD

**Issue by fudmin** [markdomansky/WebJEA#43]
Hi,

we're using webjea and it's a great tool. Thank you so much for creating this!
Unfortunately I ran into a small issue with encoding, since our servers are in german.

If I create a simple onload script, say 

`Write-Host "äöü"`

the expected output would be

`äöü`

but instead the website shows

`Ã¤Ã¶Ã¼`

This also leads to functional problems. For example if ad groups contain umlauts in their names, the webjea script won't find them. The scripts run fine if I execute them directly but not when run through webjea.

Any idea how to fix this?

**Comment by fudmin** [comment]
The following example of an onload script serves to showcase a workaround. Just in case someone else stumbles onto this issue.
A permanent solution would be great though. :)

```
$VerbosePreference = "Continue"
$DebugPreference = "Continue"

function umlauts($str) {
    $umlauts = @(
        @('Ä',[char]0x00C4),
        @('Ö',[char]0x00D6),
        @('Ü',[char]0x00DC),
        @('ä',[char]0x00E4),
        @('ö',[char]0x00F6),
        @('ü',[char]0x00FC)
    )

    foreach ($umlaut in $umlauts) {
        $str = $str -replace $umlaut[0],$umlaut[1]
    }

    return $str
}

# this will cause issues
write-host "äöü"

# this should work
write-host $(umlauts("äöü"))

# this will cause issues
Get-ADgroup "Domänen-Benutzer"

# this should work
$group = umlauts("Domänen-Benutzer")
Get-ADgroup $group
```

**Comment by fudmin** [comment]
As so often the case, mere minutes after posting about an issue online, the solution finally presents itself. No need for a fix, the issue was entirely on my side. All that is needed is to save powershell scripts with BOM enabled UTF-8 encoding.

![grafik](https://user-images.githubusercontent.com/75612123/101345789-e2b22c00-3887-11eb-9f7f-7ece619d0438.png)

After that, everything should work just fine. Don't I feel stupid now.

**Comment by markdomansky** [comment]
Glad you got it fixed.  Do you know what encoding it was in?

**Comment by fudmin** [comment]
It was set to UTF-8 without BOM by default in Notepad++. Not sure what the default editor uses.
