### ISSUE TITLE
WebJEA v1.1.157 does not show Description when clicking the 'More' button

### ISSUE THREAD

**Issue by Geo-Ron** [markdomansky/WebJEA#44]
I have WebJEA v1.1.157 and v0.9.150 running side by side in my 'test/acceptance' and production environment.

With the newest release, the button 'More' does not show anything when clicked. It changes the URL to #collapseDescription and nothing changes.

In de previous version, there was no change in the URL in your browser and the test expanded to include the DESCRIPTION of the scrip.t

**Comment by markdomansky** [comment]
I'll look into this and get back to you.

**Comment by markdomansky** [comment]
this has been fixed in the next release.
