### ISSUE TITLE
Modifying Service Account

### ISSUE THREAD

**Issue by smjdesign** [markdomansky/WebJEA#46]
Changing service account in IIS AppPool does not stick, it recycles to the original configuration. 

What is the best/proper way to modify the service account on the fly, without a new deploy? 

Is there a way to modify the Certificate Thumbprint?

Thank you!

**Comment by 1nerdyguy** [comment]
You can edit the information for both of these by editing the dscdeploy.ps1 file, where the variables are called.

**Comment by markdomansky** [comment]
1nerdyguy is correct.  This is the best option.  However, it also sounds like your LCM is configured to automatically re-apply your configuration.  This is not always desired.  If not desired, you can set the LCM not to automatically repeat the application.  See set-dsclocalconfigurationmanager.
