### ISSUE TITLE
Issues applying permissions to commands

### ISSUE THREAD

**Issue by 1nerdyguy** [markdomansky/WebJEA#47]
Having an issue applying permissions to commands using WebJeaconfig. I put in the permitted groups, such as:

`-permittedgroups @('Domainame\groupname`) -id overview`

The command takes, I save the file, go to load it with a user that is in that group, get the "you do not have permissions to this command" notice. 

I've tried domainname\\groupname, domainname\specific.user.name, and any other format I can tihnk of, just seems to not work. 

odd thing is, if I do a ('*') works like a champ, but obviously not ideal.

**Comment by markdomansky** [comment]
Can you include the relevant sections of webjea.log and and the config file (config.json usually)?
By default, nlog.config is configured to log Trace detail to webjea.log.
