### ISSUE TITLE
Webjea not accepting [mailaddress[]]$UserAccount as multiple entry field

### ISSUE THREAD

**Issue by Geo-Ron** [markdomansky/WebJEA#48]
In my script(s) I am using `[mailaddress[]]$UserAccount` as a parameter, but the form does not show a multiline form field.

`[mailaddress]$UserAccount`  and `[sring[]]$UserAccount` work as expected.

Would it be possible to accept `[mailaddress[]]$UserAccount` ?

**Comment by markdomansky** [comment]
mailaddress is not supported.
use [string[]] and then validate the addresses in the script.
