### ISSUE TITLE
Disable auto submit if page was refreshed

### ISSUE THREAD

**Issue by denispasternak** [markdomansky/WebJEA#49]
First, this is an excellent solution, which helps me a lot to give scripts so that it would be convenient to execute them with privileges that do not need to be given to the user explicitly. Thank you!

Question: is it possible to disable automatic script execution. I have a script for renaming users, and the technical support engineer says that if he refreshes the page or logs in to webJEA, then the script is automatically executed, which leads to unwanted consequences. Can this be avoided?
Thank you.

**Comment by markdomansky** [comment]
Are you using the onloadscript or the script setting in the config file.  It sounds like you've specified an onloadscript.  This is designed to run when the user loads that command.  Moving to script should fix that.  If that's not the case, can you include your config file and log file?

**Comment by denispasternak** [comment]
I do not user setting in the config file, if I'm not mistaken. Sorry I did not find what is script with the settings in config file. Perhaps I missed something.

OnloadScript parameter from config has $null value:

Script                    : C:\Scripts\webJEA\scripts\AD\rename-user.ps1
OnloadScript        : 
DisplayName        : Active Directory: rename user
Id                          : cbb824e6-83e4-40c4-aad9-c67495f867e3
PermittedGroups : {contoso\asg-webjea-cbb824e6-83e4-40c4-aad9-c67495f867e3}

Script`s parameters looks like:

Param (
    [Parameter(Position = 0, Mandatory,
    HelpMessage = 'Provide user`s email address')]
    [string]$EMail, 

    [Parameter(HelpMessage = 'Name. Example: Rick')]
    [string]$New_GivenName = "",
    [Parameter(HelpMessage = 'Surname. Example: Sanchez')]
    [string]$New_Surname = ""

    #[Parameter(Mandatory,HelpMessage="You must accept the terms")]
    #[switch]$Accept
)

Thank you.

**Comment by markdomansky** [comment]
Thinking on this further, this is behavior of the client browser and can't be prevented.  I'm considering alternatives that might circumvent this problem, but they are a long way off.

**Comment by denispasternak** [comment]
Yes, I completely agree with you. This is a browser problem. Thank you.

**Comment by denispasternak** [comment]
Thank you, your solution is really cool and very helpful.
