### ISSUE TITLE
C:\scripts\config.json file getting reset

### ISSUE THREAD

**Issue by omkarumarani** [markdomansky/WebJEA#58]
Hi Author, the C:\scripts\config.json file getting reset after we added few scripts. We have seen two scenarios
1) it just resets after half an hour so no clue why that happens
2) if we do some error while updating config then resets.

Are you aware of this and what is that we can do to stop it?

**Comment by markdomansky** [comment]
The DSC deployment script is not configured to maintain state, only for initial deployment.
See https://github.com/markdomansky/WebJEA/issues/26

**Comment by omkarumarani** [comment]
Thank you for quick and you project is life saver

**Comment by omkarumarani** [comment]
even after setting the parameter to false, it is still reseting.

**Comment by markdomansky** [comment]
You'll want to disable the local configuration manager from running every 30 minutes.
