### ISSUE TITLE
What was the intent behind MGMT1 and Web1?

### ISSUE THREAD

**Issue by oppknox** [markdomansky/WebJEA#6]
I understand web1/2 as load balancing is important, just curious as the creator  the intent of mgmt1.

Thanks!

**Comment by markdomansky** [comment]
All of these were part of my testing and presentation components.  Depending on your environment's need for LB, you may or may not need multiple servers.

**Comment by markdomansky** [comment]
I've created issue #9 to clean up this to make it easier to deploy for those not familiar with DSC.
