### ISSUE TITLE
How can I integrate git with webjea

### ISSUE THREAD

**Issue by omkarumarani** [markdomansky/WebJEA#65]
I want to make source folder available from git and any changes to file should not happen. Any suggestions

**Comment by compwiz32** [comment]
> I want to make source folder available from git 
You can specify the directory in the config that scripts are contained in. You could make a repo, clone to local machine and whatever path you save your o just needs to be updated in the webjea config file. 

> any changes to file should not happen
Sorry, I don't know what you are trying to ask. Please clarify.

**Comment by markdomansky** [comment]
@compwiz32 is correct with 1 solution.  What you're asking for is not a webjea question, but a configuration management question.  DSC, Puppet, Chef, and more could provide what you're looking for.

**Comment by omkarumarani** [comment]
Thanks for response I will follow what is said above. Yes I don't want any one modify the scripts as there is no way to identify later if that happened so better it is always synced with Git so any unauthorised changes can be prevented.
