### ISSUE TITLE
How to add a logo at top of left sidebar? 

### ISSUE THREAD

**Issue by compwiz32** [markdomansky/WebJEA#66]
I am a HTML /CSS idiot... I was looking to put a company logo above the title of the left sidebar. any instructions you could share?

**Comment by markdomansky** [comment]
Hey Mike!
I think I've got a pretty easy solution:
* Add your image to the webjea folder.
* find and edit sidebar.css
* find ```.nav-side-menu .brand {```
* Add the following inside the braces {...} :
```
width: 100%;
content:url(image..jpg);
```
You may need to adjust the sizing a bit, but it seems to work well.

**Comment by Billabongodysee** [comment]
Can confirm this works great for me!
