### ISSUE TITLE
Inconsistent permission querying, leading to redirection to overview and incorrect menu loading

### ISSUE THREAD

**Issue by mbenjamin22** [markdomansky/WebJEA#67]
This issue has been occurring since we deployed the app a few years ago (v0.9.149) but as the user base has grown the complaints now require more of an investigation

We've found that on an intermittent basis the page loads will encounter some kind of permission confusion and result in redirecting to the default page as well as the navigation menu loading someone else's permitted scripts or the ones that are available to all users

Looking in the logs I found some entries that could be causing the issue

2021-09-16 10:52:45.6503|Warn|555729||domain\user1|User domain\user2 requested page they don't have access to id6. redirecting to overview

Both users mentioned did have the access in this case, but I was wondering why it's reporting back 2 different users. It seems like there is potentially some kind of cross user query happening if multiple users are making requests at the same time? 

I can provide whatever info needed to look into this. Thank you

**Comment by markdomansky** [comment]
I'll look into this.  Off the top of my head, I can't see how there would be a cross-user query.  All the user info is pulled from native .NET resources.

**Comment by mbenjamin22** [comment]
Thanks, please let me know if you need anything.

**Comment by mbenjamin22** [comment]
Hi Mark, any progress on this one? Issue is still occurring after upgrading to latest version. Thank you

**Comment by markdomansky** [comment]
Not yet.  I'm still investigating.  WebJEA is currently a free-time project so it's only when I've got time to invest.

**Comment by markdomansky** [comment]
I have fixed this, I hope to get the build completed this weekend.

**Comment by markdomansky** [comment]
Also, thanks for your patience.  This took a lot of setup to reproduce reliably.
