### ISSUE TITLE
Extend timeout for long running scripts

### ISSUE THREAD

**Issue by Billabongodysee** [markdomansky/WebJEA#68]
We have a couple scripts that we run that take a while to return anything that WebJEA would show to the user. By the time it comes back the page throws a timeout error and gives a grey 'page not responding' or similar timeout error and you're left wondering if the script ever completed. Is there a setting somewhere to increase the time it will wait for input or the script to complete so this doesn't happen? Thanks!

**Comment by markdomansky** [comment]
That is an IIS setting.  I believe the default is 2 minutes.

```
Set-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST/Default Web Site'  -filter "system.web/httpRuntime" -name "executionTimeout" -value "hh:mm:ss"
```

**Comment by Billabongodysee** [comment]
It times out at pretty much exactly 5 minutes.  The error is "**This page isn't working right now** ourwebjea.site took too long to respond. HTTP error 504. I tried adjusting the time for that value which was at 1:50 to 7 minutes and it still times out at 5 minutes. Not sure what is causing this. Thanks for responding though.
