### ISSUE TITLE
default.aspx modification

### ISSUE THREAD

**Issue by fr0mtheinternet** [markdomansky/WebJEA#73]
I'm attempting to do simple modifications like change the page title or where the favicon is located, but no changes appear to be reflected on the website.

I've performed app pool recycling and even done an IIS reset, but nada.

My next step was going to be modifying things after load via javascript, though that's obviously a bit heavy-handed. 

Am I missing something obvious?

**Comment by markdomansky** [comment]
asp.net pages, including default.aspx, are not designed to be modified directly.  They need to be modified within the project and then compiled.
