### ISSUE TITLE
use computer alias in dscdeploy.ps1

### ISSUE THREAD

**Issue by hinakp** [markdomansky/WebJEA#75]
Can I use computer alias in the dscdeploy.ps1 instead of the actual server name?  I have setup computer alias in the domain dns.

Thank you,
Hina

**Comment by markdomansky** [comment]
DSCDeploy.ps1 is designed to use the hostname.  I'm sure it can be modified to support an FQDN different from the hostname, but it hasn't been tested.
If you try it out, let us know what you find out.

**Comment by hinakp** [comment]
Hi Mark,

Thank you for making WebJEA!  I have finally implemented WebJEA for Hyper-V VM Self-Service start/stop/restart end user's own VM.  I had to use the FQDN of the hostname.  I tried using the alias, but unfortunately, it did not work.
