### ISSUE TITLE
Endless loop when using overview.ps1

### ISSUE THREAD

**Issue by mpetereit** [markdomansky/WebJEA#79]
The starter file overview.ps1 is not working together with the new build 1.1.22173.38796

I found the problem in the PSWebHelper.vb in Line 71 to 76.
The regex cant find the correct blocks to replace in the overview.ps1 because right now there are spaces inbetween the commands.

`Links: [[a |url|display]] -[[a|?cmdid=sample1|go to sample1]]-
CSS tags in a span: [[span |cssclasses|content]] -[[span|psvariable|this span uses a variable width font and italicised]]-.
Img: [[img |cssclasses|url]] [[img||./content/ps.png]]
Nesting: [[a |url|[[img |cssclasses|url]]]] [[a|//powershell.org|[[img||./content/ps.png]]]]"`

So by example he cant find this block because there is a space after the [[a:
`[[a |url|display]]`

Correct would be:
`[[a|url|display]]`

Because he cant find the block to replace he is not updating the correct position and runns in a loop.

**Comment by markdomansky** [comment]
I should have a new release out today.
