### ISSUE TITLE
DSC problem?

### ISSUE THREAD

**Issue by smarsha** [markdomansky/WebJEA#8]
I am unable to get around a DSC error on install.  No experience with DSC.  Any idea what I am doing wrong?

$MyData = @{
    AllNodes = @(
        @{
            NodeName = '*'
            WebAppPoolName = 'WebJEA'
            AppPoolUserName = 'domain\svc-jeaadmin$'
            AppPoolPassword = "" #no credential data is actually password because we're using gMSAs
            #if you use a non-msa, use another method to set the apppool identity
            WebJEAIISURI = 'WebJEA'
            WebJEAIISFolder = 'C:\inetpub\wwwroot\webjea'
            WebJEASourceFolder = 'C:\source'
            WebJEAScriptsFolder = 'C:\scripts'
            WebJEAConfigPath = 'C:\scripts\config.json' #must be in webjeascriptsfolder
            WebJEALogPath = 'c:\scripts'
            WebJEA_Nlog_LogFile = "c:\scripts\webjea.log"
            WebJEA_Nlog_UsageFile = "c:\scripts\webjea-usage.log"
            WebJEARemoteErrors = $false
        },
        @{
            NodeName = 'MGMT1'
            Role = 'WebJEAServer'
            MachineFQDN = 'webjea1.domain.local'
            CertThumbprint = '32b66a127800958d78a5e6844d486b2ef6ab3a10'
            WebJEARemoteErrors = $false
        }
    )
}

PSDesiredStateConfiguration\Configuration : A conflict was detected between resources '[XMLConfigFile]CustomErrors (C:\Source\DSCConfig.inc.ps1::216::13::XMLConfigFile)' and 
'[XMLConfigFile]CustomErrorsRedirect (C:\Source\DSCConfig.inc.ps1::225::13::XMLConfigFile)' in node 'MGMT1'. Resources have identical key properties but there are differences in the 
following non-key properties: 'Ensure;Value;Name'. Values 'Present;RemoteOnly;mode' don't match values 'Absent;error.aspx;defaultRedirect'. Please update these property values so that they 
are identical in both cases.
At C:\Source\DSCConfig.inc.ps1:2 char:1
+ Configuration WebJEADeployment {
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], InvalidOperationException
    + FullyQualifiedErrorId : ConflictingDuplicateResource,Configuration

**Comment by markdomansky** [comment]
Looks like there was a change to xXMLConfigFile Resource that doesn't permit multiple attribute changes now.
Thankfully, this is not a required section of code.

Lines 195 to 235 for DSCConfig.inc.ps1 is an IF statement that controls remote errors.  This was added for troubleshooting.  You can comment out or remove this section of code and it should complete successfully.

**Comment by markdomansky** [comment]
I plan to remove that section and cleanup DSCDeploy.ps1 as well.

**Comment by markdomansky** [comment]
I have released an updated download that resolves the issue with the DSCConfig.ps1 error.  You can find the download [here](https://github.com/markdomansky/WebJEA/releases/download/0.9.149/webjea-0.9.149.18160-rev1.zip).

**Comment by christensenjohn** [comment]
Same issue on build 0.9.150.19126

> I have released an updated download that resolves the issue with the DSCConfig.ps1 error. You can find the download [here](https://github.com/markdomansky/WebJEA/releases/download/0.9.149/webjea-0.9.149.18160-rev1.zip).
