### ISSUE TITLE
Source bundles for build don't contain files use to make binaries

### ISSUE THREAD

**Issue by schwallers** [markdomansky/WebJEA#81]
both the zip and tar.gz bundles release with the latest build don't contain the source from the most recent build.
They contain the source from the previous build.

**Comment by markdomansky** [comment]
That may be a side-effect of how I publish builds.  I do not generate the zip or tar.gz files.  Those are automatically generated by GitHub.  I do plan to look at using GitHub Actions to build the releases, but the repo does contain the source it was built from.
