### ISSUE TITLE
Text input like HTML <tag> causes "There was an error"

### ISSUE THREAD

**Issue by AustinRozendaal** [markdomansky/WebJEA#84]
If a script is submitted with something resembling an HTML tag in a text input, the script does not run and error.aspx is shown.
```
Error on input:
- <script>
- <a>
- <asdfasdfasdf>
- </>

No error on input:
- <>
- < >
- <1234>
- <  a>
```

**Comment by AustinRozendaal** [comment]
On further experimentation, it turns out inputs like `<a` and `</` are enough to break it.

**Comment by AustinRozendaal** [comment]
Should have checked the ASP.NET logs - I didn't know that IIS blocks potentially dangerous form requests by default. After adding `<httpRuntime requestValidationMode="2.0" />` to Web.config and adding `ValidateRequest="false"` to the attributes in the Page directive at the top of default.aspx, I am able to submit with no errors.

**Comment by markdomansky** [comment]
This is an ASP.NET security feature.  disabling it is not recommended though.
