### ISSUE TITLE
stop overwriting files from source webjea

### ISSUE THREAD

**Issue by hinakp** [markdomansky/WebJEA#91]
Hi,
I updated the server.mof file to have matchsource=false but the application still overwrites files from source webjea.  How to resolve?

Thank you
HP

**Comment by markdomansky** [comment]
Your DSC Local Config Manager is likely configured to auto correct.
What does `get-dsclocalconfigurationmanager` return?

**Comment by hinakp** [comment]
It returns:
ActionAfterReboot              : ContinueConfiguration
AgentId                        : 
AllowModuleOverWrite           : False
CertificateID                  :
ConfigurationDownloadManagers  : {}
ConfigurationID                :
ConfigurationMode              : ApplyAndMonitor
ConfigurationModeFrequencyMins : 15
Credential                     :
DebugMode                      : {NONE}
DownloadManagerCustomData      :
DownloadManagerName            :
LCMCompatibleVersions          : {1.0, 2.0}
LCMState                       : PendingConfiguration
LCMStateDetail                 :
LCMVersion                     : 2.0
StatusRetentionTimeInDays      : 10
SignatureValidationPolicy      : NONE
SignatureValidations           : {}
MaximumDownloadSizeMB          : 500
PartialConfigurations          :
RebootNodeIfNeeded             : False
RefreshFrequencyMins           : 30
RefreshMode                    : PUSH
ReportManagers                 : {}
ResourceModuleManagers         : {}
PSComputerName                 :

Thanks for the help!
