### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by mrcwatling** [markdomansky/WebJEA#92]
Hi,

I am trying to install WebJEA and the deploy.ps1 script has errors as soon as I start I get the error's below

PS C:\Source> .\Deploy.ps1
At C:\Source\Deploy.ps1:37 char:5
+     Import-DSCResource -ModuleName xWebAdministration
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Could not find the module 'xWebAdministration'.
At C:\Source\Deploy.ps1:38 char:5
+     Import-DSCResource -ModuleName xXMLConfigFile
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Could not find the module 'xXMLConfigFile'.
At C:\Source\Deploy.ps1:39 char:5
+     Import-DscResource -ModuleName cUserRightsAssignment
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Could not find the module 'cUserRightsAssignment'.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : ModuleNotFoundDuringParse
 
I have the IIS and modified the script variables as noted in the install document but I am not sure what I am missing?

Is this because I am trying to install on Server 2022?

**Comment by aschwehm** [comment]
Looks like the modules are not installed and the check to install them does not work properly in your case.
Try installing the modules before executing the script:
```  
install-module xwebadministration
install-module xXMLConfigFile
install-module cUserRightsAssignment
