### ISSUE TITLE
$WebJEAHostname empty

### ISSUE THREAD

**Issue by Kdash9999** [markdomansky/WebJEA#93]
Hello, 

Someone can help me with this parameter please ? 

In my script, parameters are set like this : 
`Param(`
    `[Parameter()]`
    `[string]$WebJEAUsername,` #this won't be shown to the user
    `[Parameter()]`
    `[string]$WebJEAHostname` #this won't be shown to the user
`)`

I only get my username, client hostname is empty.
Did i miss something ? 

Thank you

**Comment by markdomansky** [comment]
The content comes from IIS and ASP.NET.  Usually, the Hostname is the same as the IP address, but if the webserver decides it should be something else, that's outside of WebJEA's control.

**Comment by CanisVY** [comment]
> The content comes from IIS and ASP.NET. Usually, the Hostname is the same as the IP address, but if the webserver decides it should be something else, that's outside of WebJEA's control.

Hi Mark, 

Posting this here as it is relevant to this question
If I call the params in my on-click script, should I be able to grab the user's name and hostname when they open the script, or is this only capable during submission?

**Comment by markdomansky** [comment]
@Kdash9999, I have one possible explanation for why this isn't working.
Is this script part of an onload script?  If so, the onload script must match the same parameters of the script property.  If $webjeahostname and $webjeausername are not part of both scripts, the onload script won't get the values.  This is a side-effect of exactly how processing was done to add onload parameter support.

@CanisVY,
Dynamic parameters are not supported.

**Comment by mpetereit** [comment]
> 

@CanisVY 
I created a Fork a while ago that supports dynamic Fields and a few other updates.
The Feature what you describe (filling a listbox depending on the Username) I just added a Week ago. Just check the Fork WebJEA-Custom

Sorry for the advertisement but a saw a few people already that asked for the dynamic Fields feature
